### ISSUE TITLE
Considerar cambiar la sección "Contenido" por "Entregable proyecto" y moverla al final

### ISSUE THREAD

**Issue by fmachadopiriz** [ucudal/ANDIS_Conceptos#35]
Justificación: Lo que está en la sección "Contenido" puede ser confuso, pues no es el contenido de los cursos sino del entregable de un proyecto final de grado. Además, si es lo primero que aparece, podría ser confuso para los estudiantes de los cursos de Análisis y diseño de aplicaciones y de Ingeniería de software que van antes.

Lo complejo puede ser el renombre de los archivos, yo lo hago si estás okay porque tengo el complemento que sincroniza el file system con los archivos .MD

Puede ser otro nombre, pero que refleje mejor el contenido de esa sección.

¿Qué te parece?

**Comment by PaoloMazza1204** [comment]
Estoy de acuerdo, sí; puede resultar confuso para ellos. "Entregable proyecto" me parece clarísimo 👍🏻.
